# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      major-updates:
        update-types:
          - "major"
      minor-updates:
        update-types:
          - "minor"
          - "patch"
      security-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      major-updates:
        update-types:
          - "major"
      minor-updates:
        update-types:
          - "minor"
          - "patch"
      security-updates:
        update-types:
          - "minor"
          - "patch"
